apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgARvqbE8O9IJvCWdPSdqgV9v0N1Twe+GMYKbmfJ4seFwf/O2dZCzV9qYEb9bw1SG3FEYLut3H/zb3MYbidwzg6FUvzMMRRPTajpwYAQub5y37F+HRiw3tXd4CeDyyELDWSURlS2mj+FbfUXPHUt/QGnkNNj1ceHeA61VBxl9j5zBjEkEoSqK5FQ0zopsSi4TZKwd0C2AlWEJwzKUlNTmu3zqwXos8Vs1KplYq2wr4YuPJJxOzWmDs0VS+1FbD3U1k0aZ/eIxKD6ixHjsFqNONRuRUQxw2m+thILZIWWl3+cSIVnMpJL9qFpbtcvGhaXbdAmwp/E+pw8uCcPVYKLNwMwJo1E1ffA3CSsasNFF5Fc3kWwAzLouOWSoFcHm3r7r68Pe5DMA8yQd9jv7bNKhih1WyywVG6A0ba2Dvu/kMgg/ahhmGu998uATrrysJpSC+p237/pfBAWCoWDlBl4BMkGwGigubsnse5T5cLazK9oW5LTPKVBphEU1qd0MHU3q8Mv4MwdoJCdwL3o8hHXbt6A8RsWIU/mat+TaMlHEmTFbcQOm1NUVl2PeC8iEwIUDQCn4sK/dPSURFca6lEhiKjJjlmshhCKlHydiYEnc0eRc5IuR6lDXE9+2FImGEiusp2Uz3OfIIVF4Wa1qWio838Talrcqf/dFcthvkTac/OHq9h3fo1NEG7A6/tpMViwfP2BAfwPq/cMfBkVAz72z2PGvwDwayK5lWqjp3YekTNZiHiiZbk1Qx/yp/x9NJZ6VihTrLTr98nGRKhq7FRTWN2fi3rBd6Iu9WzjDAE78m2hXrmLikqLN6AD/PIaTajhJPAoCMql37f70ZUqURlqzo5/IUShCBnkonzRAp/sB0A2WtI9Dj+sUQ9eBA2e9Nj+dceZnAcz+TDSpDPXYY3h7YlQRYyvzqPH+pxOIas3exs28A==
    IBM_ENTITLED_REGISTRY_USER: AgC3oi4uO1zZlc6pr2gk3VgWtJTvX+mY8tqe25kLPYrUVhA4NlrOcI2IoMYJRdw6QD3r6HHNW/ShvFuALJxytllgM+RAyXa6hS3/pjhL0d3sj2VNmsEV8ZArHiR+CLwvq3dMyT/OGVU3FHJ/wgjIQ6iGvgMC9L4tFV9Adg/RL7FpEJl6PxJ3r5dBrNyQghRGdPxgrl6YG2uHxcPyrbiuO0HGrL21n4w/TAOxVIGsSgM0QjGaQc1oBy9r2i6Gr6anrSrh9F0pAbvJOKgAsma1ECyhmv9qk+dg0VRxozwTfK09kVyGbP1ksRSo0SQE29pm23rmXOW2HfNC5nsFrQibsI2drOXvpc8gqeP+72+Pcq5qqug90XedUZ5X6fpQU5D8Oj1R9SHL61B2hc8eD194d2DMlPl/jCoqVHNyRvFHdpnxxYTC5JLQmoQsJ1ZF5rqMYzGUSTkoU8gB8MKEuoPW/TnEPuzycbyhSApNNHqFZKeJcVnBx/94W9eWoVZpYL8Q6R5nroVNb5Gzh5baXFu6XGKJ0vn6DXjkBLx5Pg59y/6kZ81rA3zlaIJrDs3u6XB6mStZMKjLryaaZQy8yDwU1DsPRGM7HLkB4gILjMfdk8t/3EhpeSNHBfy0Co51+3qIK9JpNvrRKURxyA1C3+UD/tXCjqBlKTLfq4oz0WdgDJ0GHvgiaONEMfcvtHMZcMtOZa6c5g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci
    type: Opaque

